import { loc, createCallout } from 'okta';
import { BaseForm } from '../../internals';
import BaseAuthenticatorView from '../../components/BaseAuthenticatorView';

const OV_UV_ENABLE_BIOMETRIC_SERVER_KEY = 'oie.authenticator.oktaverify.method.totp.verify.enable.biometrics';

const Body = BaseForm.extend(Object.assign(
  {
    className: 'okta-verify-totp-challenge',

    title() {
      return loc('oie.okta_verify.totp.title', 'login');
    },

    save() {
      return loc('mfa.challenge.verify', 'login');
    },

    initialize: function() {
      BaseForm.prototype.initialize.apply(this, arguments);
      this.listenTo(this.options.appState, 'afterError', (convertedErrors) => {
        // Need to wait until BaseForm renders the error so we can replace it
        setTimeout(() => {
          this._showUserVerifcationError(convertedErrors);
        });
      });
    },

    _showUserVerifcationError(convertedErrors) {
      const errorSummaryKeys = convertedErrors?.responseJSON?.errorSummaryKeys;
      if (errorSummaryKeys && errorSummaryKeys.includes(OV_UV_ENABLE_BIOMETRIC_SERVER_KEY)) {
        // remove the error generated by BaseForm
        this.model.trigger('clearFormError');
        // add custom error for User Verification
        this.add('<div class="ion-messages-container"></div>', '.o-form-error-container');
        const options = {
          type: 'error',
          className: 'okta-verify-uv-callout-content',
          title: loc('oie.authenticator.app.method.push.verify.enable.biometrics.title', 'login'),
          subtitle: loc('oie.authenticator.app.method.push.verify.enable.biometrics.description', 'login'),
          bullets: [
            loc('oie.authenticator.app.method.push.verify.enable.biometrics.point1', 'login'),
            loc('oie.authenticator.app.method.push.verify.enable.biometrics.point2', 'login'),
            loc('oie.authenticator.app.method.push.verify.enable.biometrics.point3', 'login')
          ],
        };
        this.add(createCallout(options), '.o-form-error-container');
      }
    },
  },
));

export default BaseAuthenticatorView.extend({
  Body,
});
