test_suites:
    - name: publish
      script_path: /root/okta/okta-signin-widget/scripts
      sort_order: '1'
      timeout: '15'
      script_name: publish
      criteria: MERGE
      queue_name: small
    - name: verify-package
      script_path: /root/okta/okta-signin-widget/scripts
      sort_order: '2'
      timeout: '15'
      script_name: verify-package
      criteria: MERGE
      queue_name: small
    - name: lint
      script_path: /root/okta/okta-signin-widget/scripts
      sort_order: '3'
      timeout: '10'
      script_name: lint
      criteria: MERGE
      queue_name: small
    - name: unit-jest
      script_path: /root/okta/okta-signin-widget/scripts
      sort_order: '4'
      timeout: '15'
      script_name: unit-jest
      criteria: MERGE
      queue_name: small
    - name: testcafe
      script_path: /root/okta/okta-signin-widget/scripts
      sort_order: '5'
      timeout: '30'
      script_name: testcafe
      criteria: MERGE
      queue_name: small
    - name: e2e
      script_path: /root/okta/okta-signin-widget/scripts
      sort_order: '6'
      timeout: '20'
      script_name: e2e
      criteria: MERGE
      queue_name: small
    - name: e2e-lang
      script_path: /root/okta/okta-signin-widget/scripts
      sort_order: '6'
      timeout: '20'
      script_name: e2e-lang
      criteria: MERGE
      queue_name: small
      # FIXME: revert criteria to "MERGE" when merging 0.0 to master
    - name: e2e-saucelabs
      script_path: /root/okta/okta-signin-widget/scripts
      sort_order: '6'
      timeout: '20'
      script_name: e2e-saucelabs
      criteria: OPTIONAL
      queue_name: small
    - name: tsd
      script_path: /root/okta/okta-signin-widget/scripts
      sort_order: '7'
      timeout: '15'
      script_name: tsd
      criteria: MERGE
      queue_name: small
    - name: detect-english-leaks
      script_path: /root/okta/okta-signin-widget/scripts
      sort_order: '8'
      timeout: '20'
      script_name: detect-english-leaks
      criteria: MERGE
      queue_name: small
    - name: unit-karma
      script_path: /root/okta/okta-signin-widget/scripts
      sort_order: '9'
      timeout: '15'
      script_name: unit-karma
      criteria: MERGE
      queue_name: small
    - name: lint-v3
      script_path: /root/okta/okta-signin-widget/scripts
      sort_order: '10'
      timeout: '15'
      script_name: lint-v3
      criteria: MERGE
      queue_name: small
    - name: unit-v3
      script_path: /root/okta/okta-signin-widget/scripts
      sort_order: '10'
      timeout: '15'
      script_name: unit-v3
      criteria: MERGE
      queue_name: small
      # NOTE: runs the testcafe suite within v3
    - name: e2e-v3
      script_path: /root/okta/okta-signin-widget/scripts
      sort_order: '10'
      timeout: '15'
      script_name: e2e-v3
      criteria: MERGE
      queue_name: small
    # NOTE: runs the testcafe suite at the project root to ensure parity between
    # v2 and v3 for select flows
    - name: v3-parity
      script_path: /root/okta/okta-signin-widget/scripts
      sort_order: '5'
      timeout: '30'
      script_name: v3-parity
      criteria: MERGE
      queue_name: small

