test_suites:
  - name: publish
    script_path: /root/okta/okta-signin-widget/scripts
    sort_order: '1'
    timeout: '15'
    script_name: publish
    criteria: MERGE
    queue_name: small
  - name: verify-package
    script_path: /root/okta/okta-signin-widget/scripts
    sort_order: '2'
    timeout: '15'
    script_name: verify-package
    criteria: MERGE
    queue_name: small
  - name: lint
    script_path: /root/okta/okta-signin-widget/scripts
    sort_order: '3'
    timeout: '10'
    script_name: lint
    criteria: MERGE
    queue_name: small
  - name: unit-jest
    script_path: /root/okta/okta-signin-widget/scripts
    sort_order: '4'
    timeout: '20'
    script_name: unit-jest
    criteria: MERGE
    queue_name: small
  - name: testcafe
    script_path: /root/okta/okta-signin-widget/scripts
    sort_order: '5'
    timeout: '30'
    script_name: testcafe
    criteria: MERGE
    queue_name: small
  - name: lint-v3
    script_path: /root/okta/okta-signin-widget/scripts
    sort_order: '6'
    timeout: '15'
    script_name: lint-v3
    criteria: MERGE
    queue_name: small
  - name: unit-v3
    script_path: /root/okta/okta-signin-widget/scripts
    sort_order: '7'
    timeout: '15'
    script_name: unit-v3
    criteria: MERGE
    queue_name: small
    # NOTE: runs the testcafe suite within v3
  - name: e2e-v3
    script_path: /root/okta/okta-signin-widget/scripts
    sort_order: '8'
    timeout: '15'
    script_name: e2e-v3
    criteria: MERGE
    queue_name: small
  # NOTE: runs the testcafe suite at the project root to ensure parity between
  # v2 and v3 for select flows
  - name: parity-v3
    script_path: /root/okta/okta-signin-widget/scripts
    sort_order: '9'
    timeout: '40'
    script_name: parity-v3
    criteria: MERGE
    queue_name: small
  - name: e2e
    script_path: /root/okta/okta-signin-widget/scripts
    sort_order: '10'
    timeout: '40'
    script_name: e2e
    criteria: MERGE
    queue_name: small
  - name: e2e-lang
    script_path: /root/okta/okta-signin-widget/scripts
    sort_order: '11'
    timeout: '30'
    script_name: e2e-lang
    criteria: MERGE
    queue_name: small
  - name: e2e-saucelabs
    script_path: /root/okta/okta-signin-widget/scripts
    sort_order: '12'
    timeout: '20'
    script_name: e2e-saucelabs
    criteria: MERGE
    queue_name: small
  # Optional test suite until Android is enabled
  - name: e2e-saucelabs-mobile
    script_path: /root/okta/okta-signin-widget/scripts
    sort_order: '13'
    timeout: '20'
    script_name: e2e-saucelabs-mobile
    criteria: OPTIONAL
    queue_name: small
  - name: tsd
    script_path: /root/okta/okta-signin-widget/scripts
    sort_order: '14'
    timeout: '15'
    script_name: tsd
    criteria: MERGE
    queue_name: small
  - name: detect-english-leaks
    script_path: /root/okta/okta-signin-widget/scripts
    sort_order: '15'
    timeout: '20'
    script_name: detect-english-leaks
    criteria: MERGE
    queue_name: small
  - name: verify-registry-install
    prereq_test_suite_name: publish
    script_path: /root/okta/okta-signin-widget/scripts
    sort_order: '17'
    timeout: '20'
    script_name: verify-registry-install
    criteria: MERGE
    queue_name: small
  - name: find-internal-packages
    script_path: /root/okta/okta-signin-widget/scripts
    sort_order: '18'
    timeout: '20'
    script_name: find-internal-packages
    criteria: MERGE
    queue_name: small
  # E2E tests using dockerized monolith - optional (for now)
  - name: e2e-monolith
    script_path: ../okta-signin-widget/scripts
    sort_order: '19'
    timeout: '30'
    script_name: e2e-monolith
    criteria: OPTIONAL
    queue_name: ci-queue-prodJenga-Monolith-Build
  - name: semgrep
    script_path: /root/okta/okta-signin-widget/scripts
    sort_order: '31'
    timeout: '10'
    script_name: semgrep
    script_env: {}
    criteria: MERGE
    queue_name: small
  # This suite runs the UI components demo VRT
  # Usage wiki: https://oktawiki.atlassian.net/wiki/spaces/eng/pages/2855600129/Odyssey+1.x+migration+testcafe+VRT+usage
  - name: vrt-v3
    script_path: /root/okta/okta-signin-widget/scripts
    sort_order: '32'
    timeout: '15'
    script_name: vrt-v3
    criteria: MERGE
    queue_name: small
  # This bacon script can be used to get new base screenshots without having to run the VRT
  - name: vrt-v3-get-screenshots
    script_path: /root/okta/okta-signin-widget/scripts
    sort_order: '33'
    timeout: '15'
    script_name: vrt-v3-get-screenshots
    criteria: OPTIONAL
    queue_name: small
