test_suites:
  - name: publish
    sort_order: "1"
    script_path: /root/okta/okta-signin-widget/scripts
    timeout: "20"
    script_name: publish
    criteria: MERGE
    queue_name: small
  - name: verify-package
    sort_order: "2"
    script_path: /root/okta/okta-signin-widget/scripts
    timeout: "20"
    script_name: verify-package
    # https://oktainc.atlassian.net/browse/OKTA-545411
    criteria: OPTIONAL
    queue_name: small
  - name: lint
    sort_order: "3"
    script_path: /root/okta/okta-signin-widget/scripts
    timeout: "20"
    script_name: lint
    criteria: MERGE
    queue_name: small
  - name: unit-jest
    sort_order: "4"
    script_path: /root/okta/okta-signin-widget/scripts
    timeout: "30"
    script_name: unit-jest
    criteria: MERGE
    queue_name: small
  - name: testcafe
    sort_order: "5"
    script_path: /root/okta/okta-signin-widget/scripts
    timeout: "60"
    script_name: testcafe
    criteria: MERGE
    queue_name: small
  - name: e2e
    sort_order: "6"
    script_path: /root/okta/okta-signin-widget/scripts
    timeout: "60"
    script_name: e2e
    criteria: MERGE
    queue_name: small
  - name: e2e-lang
    sort_order: "7"
    script_path: /root/okta/okta-signin-widget/scripts
    timeout: "40"
    script_name: e2e-lang
    criteria: MERGE
    queue_name: small
  - name: e2e-saucelabs
    sort_order: "8"
    script_path: /root/okta/okta-signin-widget/scripts
    timeout: "40"
    script_name: e2e-saucelabs
    criteria: MERGE
    queue_name: small
  # Optional test suite until Android is enabled
  - name: e2e-saucelabs-mobile
    sort_order: "9"
    script_path: /root/okta/okta-signin-widget/scripts
    timeout: "40"
    script_name: e2e-saucelabs-mobile
    criteria: OPTIONAL
    queue_name: small
  - name: tsd
    sort_order: "10"
    script_path: /root/okta/okta-signin-widget/scripts
    timeout: "30"
    script_name: tsd
    criteria: MERGE
    queue_name: small
  - name: detect-english-leaks
    sort_order: "11"
    script_path: /root/okta/okta-signin-widget/scripts
    timeout: "40"
    script_name: detect-english-leaks
    criteria: MERGE
    queue_name: small
  - name: unit-karma
    sort_order: "12"
    script_path: /root/okta/okta-signin-widget/scripts
    timeout: "30"
    script_name: unit-karma
    criteria: MERGE
    queue_name: small
  - name: verify-registry-install
    prereq_test_suite_name: publish
    sort_order: "13"
    script_path: /root/okta/okta-signin-widget/scripts
    timeout: "40"
    script_name: verify-registry-install
    criteria: MERGE
    queue_name: small
  # E2E tests using dockerized monolith - optional (for now)
  - name: e2e-monolith
    sort_order: "14"
    script_path: ../okta-signin-widget/scripts
    timeout: "60"
    script_name: e2e-monolith
    criteria: OPTIONAL
    queue_name: ci-queue-prodJenga-Monolith-Build
  - name: lint-v3
    sort_order: "15"
    script_path: /root/okta/okta-signin-widget/scripts
    timeout: "30"
    script_name: lint-v3
    criteria: MERGE
    queue_name: small
  - name: unit-v3
    sort_order: "16"
    script_path: /root/okta/okta-signin-widget/scripts
    timeout: "30"
    script_name: unit-v3
    criteria: MERGE
    queue_name: small
    # NOTE: runs the testcafe suite within v3
  - name: e2e-v3
    sort_order: "17"
    script_path: /root/okta/okta-signin-widget/scripts
    timeout: "30"
    script_name: e2e-v3
    criteria: MERGE
    queue_name: small
  # NOTE: runs the testcafe suite at the project root to ensure parity between
  # v2 and v3 for select flows
  - name: parity-v3
    sort_order: "18"
    script_path: /root/okta/okta-signin-widget/scripts
    timeout: "60"
    script_name: parity-v3
    criteria: MERGE
    queue_name: small
