enableMessageNames: false

nodeLinker: node-modules

npmAuditRegistry: "https://artifacts.aue1e.internal/artifactory/api/npm/npm-okta-master"

npmRegistryServer: "https://artifacts.aue1e.internal/artifactory/api/npm/npm-okta-master"

npmAlwaysAuth: true # <---- new line

npmScopes:
  okta:
    npmPublishRegistry: "https://artifacts.aue1e.internal/artifactory/api/npm/npm-topic"
    npmRegistryServer: "${OKTA_NPM_REGISTRY_SERVER-https://artifacts.aue1e.internal:443/artifactory/api/npm/npm-okta-master}"
    npmAlwaysAuth: true
    npmAuthToken: "${NPM_TOKEN}"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-engines.cjs
    spec: "https://raw.githubusercontent.com/devoto13/yarn-plugin-engines/main/bundles/%40yarnpkg/plugin-engines.js"

yarnPath: .yarn/releases/yarn-3.6.4.cjs

