define([
  'okta/jquery',
  'okta/underscore',
  'shared/views/BaseView',
  'shared/views/components/BaseModalDialog',
  'shared/views/forms/BaseForm'
],
function ($, _, BaseView, BaseModalDialog, BaseForm) {

  var FORM_FIELDS = [
    'save',
    'noCancelButton',
    'inputs',
    'subtitle',
    'autoSave',
    'focus',
    'cancel',
    'danger',
    'hasSavingState',
    'customSavingState',
    'parseErrorMessage'
  ];
  var FORM_DEFAULTS = {
    layout: 'o-form-wrap',
    scrollOnError: false
  };

  // jquery.simplemodoal options
  var SIMPLE_MODAL_PARAMS = {
    minWidth: 600,
    maxWidth: 950,
    focus: false,
    close: false,
    autoResize: false, // (use the resizeModal method, so that the scrolling goes to content, not the whole modal)
    autoPosition: true
  };

  /**
   * Okta.FormDialog is a facade layer for a form that lives in a modal dialog.
   *
   * The API is proxying the {@link module:Okta.Form|Form} API for the most part.
   * It also triggers all the form events
   * It takes care of repositioning, resizing, closing the dialog on cancel, and so on.
   *
   * @class module:Okta.FormDialog
   * @extends module:Okta.View
   * @borrows module:Okta.Form#event:save as save
   * @borrows module:Okta.Form#event:saved as saved
   * @borrows module:Okta.Form#event:resize as resize
   * @borrows module:Okta.Form#event:cancel as cancel
   * @borrows module:Okta.Form#title as #title
   * @borrows module:Okta.Form#subtitle as #subtitle
   * @borrows module:Okta.Form#save as #save
   * @borrows module:Okta.Form#inputs as #inputs
   * @borrows module:Okta.Form#noCancelButton as #noCancelButton
   * @borrows module:Okta.Form#autoSave as #autoSave
   * @borrows module:Okta.ModalDialog#params as #params
   * @borrows module:Okta.Form#addInput as #addInput
   * @borrows module:Okta.Form#addButton as #addButton
   * @borrows module:Okta.Form#addDivider as #addDivider
   * @borrows module:Okta.Form#addSectionTitle as #addSectionTitle
   * @borrows module:Okta.Form#clearErrors as #clearErrors
   * @example
   * var AddUserDialog = Okta.FormDialog({
   *   autoSave: true,
   *   title: 'Add a User',
   *   inputs: [
   *     {
   *       type: 'text',
   *       name: 'fname',
   *       label: 'First Name'
   *     },
   *     {
   *       type: 'text',
   *       name: 'lname',
   *       label: 'Last Name'
   *     }
   *   ]
   * });
   *
   * // renders the modal dialog on the page
   * var dialog = new AddUserDialog({model: new MyModel()}).render();
   * this.listenTo(dialog, 'saved', function (model) {
   *   // the model is now saved
   * });
   */
  return BaseView.extend(/** @lends module:Okta.FormDialog.prototype */ {

    constructor: function (options) {
      /* eslint max-statements: [2, 13] */

      var Form = BaseForm.extend(_.extend({}, FORM_DEFAULTS, _.pick(this, FORM_FIELDS)));
      this.form = new Form(_.omit(options, 'title', 'subtitle'));

      this.listenTo(this.form, 'resize', _.debounce(_.bind(this.resizeModal, this), 100));

      // trigger all form events
      var removeFn = _.bind(this.remove, this);
      this.listenTo(this.form, 'all', function () {
        this.trigger.apply(this, arguments);
        if (arguments[0] === 'cancel') {
          removeFn();
        }
      });

      $(window).resize(_.debounce(_.bind(this.resizeModal, this), 100));

      var Dialog = BaseModalDialog.extend({
        title: this.title,
        className: this.className,
        params: _.extend({}, SIMPLE_MODAL_PARAMS, this.params)
      });

      this.dialog = new Dialog(options);
      this.dialog.add(this.form);
      this.el = this.dialog.el;


      BaseView.apply(this, arguments);

      if (this.form.getAttribute('autoSave')) {
        this.listenTo(this, 'saved', this.remove);
      }

    },

    /**
     * The form instance generated by the constructor.
     * Should **not** be referenced locally, exposed externally for test purposes.
     * @type {Okta.Form}
     * @private
     * @readonly
     */
    form: undefined,

    /**
     * The dialog instance generated by the constructor.
     * Should **not** be referenced locally, exposed externally for test purposes.
     * @type {Okta.ModalDialog}
     * @private
     * @readonly
     */
    dialog: undefined,

    addInput: function () {
      return this.form.addInput.apply(this.form, arguments);
    },

    addButton: function () {
      return this.form.addButton.apply(this.form, arguments);
    },

    addDivider: function () {
      return this.form.addDivider.apply(this.form, arguments);
    },

    addSectionTitle: function () {
      return this.form.addSectionTitle.apply(this.form, arguments);
    },

    add: function () {
      return this.form.add.apply(this.form, arguments);
    },

    render: function () {
      this.preRender();
      this.dialog.render.apply(this.dialog, arguments);
      _.defer(_.bind(this.resizeModal, this));
      this.postRender();
      return this;
    },

    remove: function () {
      this.dialog.remove.apply(this.dialog, arguments);
      return BaseView.prototype.remove.apply(this, arguments);
    },

    /**
     * Resize modal to fit window height
     * the whole modal will be within the viewport, only the form content is scrollable
     * there's no good solution to totally fix the width issue yet for tiny window,
     * leave it for jquery simplemodal autoResize to do its best
     */
    resizeModal: function () {
      var modal = $('.simplemodal-wrap'),
          form = this.form,
          modalHeight = modal.height(),
          modalMinHeight = _.isNumber(this.dialog.params.minHeight) ? this.dialog.params.minHeight : 0,
          windowHeight = $(window).height();
      if (modalMinHeight <= modalHeight) {
        if (modalHeight >= windowHeight) {
          form.contentHeight(
            windowHeight - this.dialog.$('h2').outerHeight() - form.$('.o-form-button-bar').outerHeight() -
            (modal.outerHeight(true) - form.$el.outerHeight(true)));
        }
        else {
          form.contentHeight(
            form.contentHeight() + (windowHeight - modalHeight) - (modal.outerHeight() - modalHeight)
          );
        }
        this.dialog.resize.apply(this.dialog, arguments);
      }
    },

    clearErrors: function () {
      return this.form.clearErrors.apply(this.form, arguments);
    }

  });

});
