/*
 * Copyright (c) 2022-present, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 */

import * as Tokens from '@okta/odyssey-design-tokens';
import chroma from 'chroma-js';

import { createThemeAndTokens, generatePalette } from './theme';

const WHITE_HEX = '#ffffff';
// Odyssey-defined contrast ratios for their WCAG-friendly palettes
const ODYSSEY_RATIOS = [1.1, 1.31, 1.61, 2.22, 3.32, 4.5, 4.95, 8.72, 11.73, 14.94];

describe('theme utilities', () => {
  describe('generatePalette', () => {
    it('generates a palette with Odyssey contrast ratios', () => {
      const palette = generatePalette('#546Be7');
      expect(palette).toBeDefined();
      expect(Object.keys(palette!).length).toBe(10);
      const contrastRatios = Object.values(palette!).map((hue) => chroma.contrast(hue, WHITE_HEX));
      // Precision of 0.5 maps to 0.2 as an allowed deviation to account for differences between
      // chroma.contrast() and Leonardo's calculations
      contrastRatios.forEach((ratio, i) => expect(ratio).toBeCloseTo(ODYSSEY_RATIOS[i], 0.5));
    });

    it('returns null for invalid colors', () => {
      // suppress warnings from when chroma-js throws
      jest.spyOn(console, 'warn').mockImplementation(() => { });

      expect(generatePalette('#12345')).toBeNull();
      expect(generatePalette('#ff00gg')).toBeNull();
      expect(generatePalette('')).toBeNull();

      jest.restoreAllMocks();
    });
  });

  describe('createThemeAndTokens', () => {
    // Explicitly construct OD 1.x palette because odyssey-react-mui palette's 'dark' is
    // different than Tokens.PalettePrimaryDark
    const defaultOdyPrimaryPalette = {
      main: Tokens.PalettePrimaryMain,
      light: Tokens.PalettePrimaryLight,
      lighter: Tokens.PalettePrimaryLighter,
      dark: Tokens.HueBlue900,
      contrastText: Tokens.TypographyColorInverse,
    };

    it('should use brandColors.primaryColor to set PalettePrimary.* tokens', () => {
      const primaryColor = '#7950f2';
      const palette = generatePalette(primaryColor);
      const { tokensOverride: tokens } = createThemeAndTokens({ primaryColor });
      // Pick a subset of the overridden primary-related design tokens to assert on
      expect(tokens.PalettePrimaryMain).toEqual(palette?.CustomHue500);
      expect(tokens.PalettePrimaryDark).toEqual(palette?.CustomHue700);
      expect(tokens.TypographyColorAction).toEqual(palette?.CustomHue600);
    });

    it('should ignore brandColors if undefined and use default Odyssey theme', () => {
      const { themeOverride: theme } = createThemeAndTokens();
      expect(theme.palette?.primary).toEqual(defaultOdyPrimaryPalette);
    });

    it('should ignore brandColors.primaryColor if invalid', () => {
      // suppress warnings from when @adobe/leonardo-contrast-color throws
      jest.spyOn(console, 'warn').mockImplementation(() => { });
      const primaryColor = '#invalid';
      const { themeOverride: theme } = createThemeAndTokens({ primaryColor });
      expect(theme.palette?.primary).toEqual(defaultOdyPrimaryPalette);
    });

    it('should not set palette tokens generated by brandColors for design tokens that are already set', () => {
      // #ff3d3d is a bright red, #7950f2 is a bright purple
      const { tokensOverride: tokens } = createThemeAndTokens({ primaryColor: '#ff3d3d' }, { PalettePrimaryMain: '#7950f2' });
      // PalettePrimaryMain should be #7950f2 since it is specifically overridden but the remainder
      // of the palette tokens should be red hues
      expect(tokens.PalettePrimaryMain).toEqual('#7950f2');
      // #8e2222 is a medium red hue
      expect(tokens.PalettePrimaryDark).toEqual('#8e2222');
      // #fff0f0 is a very pale red
      expect(tokens.PalettePrimaryLighter).toEqual('#fff0f0');
    });

    it('should override non-palette Odyssey default theme values with custom tokens', () => {
      const customTokens = {
        BorderRadiusMain: '1rem',
        TypographyColorHeading: '#77216f',
      };
      const { themeOverride: theme } = createThemeAndTokens(undefined, customTokens);
      expect(theme.mixins?.borderRadius).toEqual(customTokens.BorderRadiusMain);
      // @ts-expect-error Odyssey theme sets heading colors by default
      expect(theme.typography?.h1.color).toEqual(customTokens.TypographyColorHeading);
    });
  });
});
